site_name: SuperComputing Luxembourg - National Competence Center

nav:
    - Trainings organization: 'index.md'
    - Courses:
        - Course catalogue: 'courses/index.md'
#       - AI with HPC:
#           - Distributed Deep Learning:
#               - Introduction: 'openacc/index.md'
#       - Computational Chemistry:
#           - Quantum Espresso:
#               - Introduction: 'openacc/index.md'
#       - Julia:
#           - Introduction: 'julia/index.md'
#       - Numerical Libraries:
#           - Quantum Espresso:
#               - Introduction: 'openacc/index.md'
#       - Other Accelerators:
#           - Introduction: 'openacc/index.md'
        - Parallel Programming:
            - CPU:
                - OpenMP:
                    - Introduction: 'openmp/index.md'
                    - Preparation: 'openmp/preparation.md'
                    - Hands-On:
                        - Parallel Region: 'openmp/exercise-1.md'
                        - Data Sharing Attribute: 'openmp/exercise-2.md'
                        - Work Sharing Constructs(loop): 'openmp/exercise-3.md'
                        - Work Sharing Constructs(loop-scheduling): 'openmp/exercise-4.md'
                        - Worksharing Constructs(others): 'openmp/exercise-5.md'
                        - SIMD and Others: 'openmp/exercise-6.md'
                        - Profiling and Performance: 'openmp/profiling.md'
            - GPU:
                - CUDA:
                    - Introduction: 'cuda/index.md'
                    - Preparation: 'cuda/preparation.md'
                    - Hands-On:
                        - Hello World: 'cuda/exercise-1.md'
                        - Vector Addition: 'cuda/exercise-2.md'
                        - Matrix Multiplication: 'cuda/exercise-3.md'
                        - Shared Memory: 'cuda/exercise-4.md'
                        - Unified Memory: 'cuda/exercise-5.md'
                        - Profiling and Performance: 'cuda/profiling.md'
                - OpenACC:
                    - Introduction: 'openacc/index.md'
                    - Preparation: 'openacc/preparation.md'
                    - Hands-On:
                        - Compute Constructs and Paralleize Loops: 'openacc/exercise-1.md'
                        - Data Locality: 'openacc/exercise-2.md'
                        - Optimize Loops: 'openacc/exercise-3.md'
                        - Unified Memory: 'openacc/exercise-4.md'
                        - Profiling and Performance: 'openacc/profiling.md'
        - Python in the HPC:
            - Jupyter server and parallel libraries: 'python/index.md'
        - Environment management and containers:
            - Introduction: 'courses/containerization/index.md'
            - Containers: 'courses/containerization/containers.md'
            - Environment managers: 'courses/containerization/conda.md'
#           - Package management in R: 'courses/containerization/R.md'
#               - Best practices in environment management: 'environment/best-practises.md'
#               - Containers in HPC systems:
    - Bootcamp:
        - AI:
            - Introduction: 'Bootcamps/ai/introduction.md'
            - Preparation: 'Bootcamps/ai/preparation.md'
            - Hands-on: 'Bootcamps/ai/handson.md'
    - Hackathons:
        - HPDA:
            - Introduction: 'Hackathons/hpda/introduction.md'
    - Instructions for Educators:
          - Introduction: 'education/introduction.md'
          - Requirements: 'education/requirements.md'
    - Calendar:
          - Future Events: 'calendar/future.md'
          - Past Events: 'calendar/past.md'
    - Other Training Events: 'other-training/othertraining.md'

markdown_extensions:
    - attr_list
    - md_in_html
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - tables

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
    name: material
    logo: 'figures/Logo_SC_Luxembourg.png'
    features:
        - navigation.footer
        - navigation.instant
        - navigation.tracking
        - content.action.edit
        - content.action.view
        - navigation.tabs
        - navigation.top
        - navigation.indexes
        - header.autohide
        - toc.follow
        - content.code.copy
        - content.code.select
        - content.code.annotate
#   palette:
#       - primary: black
    language: en
    palette:
        primary: blue
        accent:  light blue
    palette:
        # Palette toggle for light mode
        - scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        # Palette toggle for dark mode
        - scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    features:
#       - navigation.instant
        - navigation.tabs
        - navigation.footer
    icon:
        admonition:
            note: octicons/tag-16
            abstract: octicons/checklist-16
            info: octicons/info-16
            tip: octicons/squirrel-16
            success: octicons/check-16
            question: octicons/question-16
            warning: octicons/alert-16
            failure: octicons/x-circle-16
            danger: octicons/zap-16
            bug: octicons/bug-16
            example: octicons/beaker-16
            quote: octicons/quote-16
        repo: fontawesome/brands/git-alt
        edit: material/pencil
        view: material/eye

# Extensions
markdown_extensions:
    - meta
    - attr_list
    - md_in_html
    - footnotes
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols:
        fractions: false
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.snippets
    - pymdownx.tabbed:
        alternate_style: true
    # code blocks with syntax highlighting, graphs
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    # clickable details
    - pymdownx.details
    # tabbed contents
    - pymdownx.tabbed
    - toc:
        permalink: true
    - pymdownx.keys
    - pymdownx.highlight:
        linenums_style: pymdownx.inline
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.arithmatex:
        generic: true

plugins:
    - search:
#        prebuild_index: false
    - minify:
        minify_html: true
#   - info
    - glightbox
    - git-revision-date-localized:
        type: datetime
        custom_format: "%d. %B %Y"
        timezone: Europe/Amsterdam
        locale: en
        fallback_to_build_date: false
        enable_creation_date: true
        enabled: true
        strict: true

# Extra stylesheets (incl. Twitter Bootstrap)
extra_css:
#   - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
    - stylesheets/extra.css
#   - stylesheets/bootstrap.min.css
#   - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css

extra:
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/EuroCC_Lux
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/company/eurocc-luxembourg/
    version:
        provider: mike
        default: stable
    analytics:
        provider: google
        property: G-Q3V4FYR53V
        feedback:
            title: Was this page helpful?
            ratings:
                - icon: material/emoticon-happy-outline
                  name: This page was helpful
                  data: 1
                  note: >-
                      Thanks for your feedback!
                - icon: material/emoticon-sad-outline
                  name: This page could be improved
                  data: 0
                  note: >-
                      Thanks for your feedback! Help us improve this page by
                      using our <a href="https://github.com/NCCLUX/NCC-Trainings/issues/new?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.

copyright: Copyright &copy; 2023-2025 <a href="https://supercomputing.lu/">SuperComputing Luxembourg</a>

repo_name: NCCLUX/NCC-Trainings
repo_url: https://github.com/NCCLUX/NCC-Trainings.git
edit_uri: -/edit/master/NCC-Trainings/
